### ISSUE TITLE
App crash when trying to open file movie

### ISSUE THREAD

**Issue by dzami** [0xFireball/Enlightened#32]
PROJECT INFO
repositories:
https://github.com/0xFireball/Enlightened

 EXPECTED BEHAVIOR
 The users should be able to open file movie in this app and do something with that file.

 ACTUAL BEHAVIOR
when the users trying to open file and choose to take file movie then the app has stopped and getting crashed.

HOW TO REPRODUCE
1.install enlightened on playstore
2.open the app and click on option
3.click open file
4.choose a movie in the folder
5.when the processing then the app getting crashed.
Browser: Enlightened  version:1.10
Device: android 7.0

 BUG RECORDING
https://youtu.be/8hDDenhBiZY

 LOGCATS
```E/AndroidRuntime( 4586): 	at xyz.iridiumion.enlightened.b.a.a(Unknown Source)
E/AndroidRuntime( 4586): 	at xyz.iridiumion.enlightened.activity.MainActivity.onActivityResult(Unknown Source)
I/ActivityManager(  478): Process xyz.iridiumion.enlightened (pid 4586) (adj 9) has died.
V/f       ( 6541): 1) b@41c9c8d8{[android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE], pGrantedListener=xyz.iridiumion.enlightened.activity.MainActivity$7@41c9d038, pRefusedListener=xyz.iridiumion.enlightened.activity.MainActivity$6@41c9d668, pResultListener=null, rationaleListener=null}
V/f       ( 6541): processing: b@41c9c8d8{[android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE], pGrantedListener=xyz.iridiumion.enlightened.activity.MainActivity$7@41c9d038, pRefusedListener=xyz.iridiumion.enlightened.activity.MainActivity$6@41c9d668, pResultListener=null, rationaleListener=null}
I/dalvikvm( 6541):   at xyz.iridiumion.enlightened.b.a.a((null):-1)
I/dalvikvm( 6541):   at xyz.iridiumion.enlightened.activity.MainActivity.onActivityResult((null):-1)
E/AndroidRuntime( 6541): 	at xyz.iridiumion.enlightened.b.a.a(Unknown Source)
E/AndroidRuntime( 6541): 	at xyz.iridiumion.enlightened.activity.MainActivity.onActivityResult(Unknown Source)
I/ActivityManager(  478): Process xyz.iridiumion.enlightened (pid 6541) (adj 10) has died.```

**Comment by 0xFireball** [comment]
this is a text editor, not a movie player.
